# create binary
FROM golang:1.10.1 AS builder

COPY . /go/src/github.com/superioz/gochat/
WORKDIR /go/src/github.com/superioz/gochat/

RUN set -x && \
    go get github.com/golang/dep/cmd/dep && \
    dep ensure -v

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o server /go/src/github.com/superioz/gochat/cmd/server/server.go

# create the container image
FROM alpine
COPY --from=builder /go/src/github.com/superioz/gochat/server .

EXPOSE 6000
ENTRYPOINT ["./server"]
